# Generated by Django 3.1.3 on 2020-12-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=120)),
                ('profile_image_url', models.TextField()),
                ('profile_url', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=5)),
                ('followers_count', models.PositiveIntegerField()),
                ('friends_count', models.PositiveIntegerField()),
                ('created', models.DateTimeField()),
                ('allow_all_comment', models.BooleanField()),
                ('avatar', models.TextField()),
                ('verified_reason', models.TextField()),
                ('credit_score', models.PositiveIntegerField()),
                ('user_ability', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeiboPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.PositiveBigIntegerField()),
                ('create', models.DateTimeField()),
                ('text', models.TextField()),
                ('source', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weibo.weibouser')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weibo.weibopost')),
            ],
        ),
        migrations.CreateModel(
            name='PostPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=30)),
                ('order', models.PositiveSmallIntegerField()),
                ('url', models.TextField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weibo.weibopost')),
            ],
        ),
    ]
