# Generated by Django 3.1.3 on 2020-12-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0002_auto_20201216_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weibopost',
            options={'ordering': ('-create',)},
        ),
    ]
