# Generated by Django 3.1.3 on 2020-12-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=15)),
                ('nickname', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=120)),
                ('profile_image_url', models.TextField()),
                ('profile_url', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=5)),
                ('followers_count', models.PositiveIntegerField()),
                ('friends_count', models.PositiveIntegerField()),
                ('created', models.DateTimeField()),
                ('allow_all_comment', models.BooleanField()),
                ('avatar', models.TextField()),
                ('verified_reason', models.TextField()),
                ('credit_score', models.PositiveIntegerField()),
                ('user_ability', models.PositiveIntegerField()),
            ],
        ),
    ]
