# Generated by Django 3.1.3 on 2020-12-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo-auth', '0002_auto_20201216_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weiboaccount',
            name='user_ability',
            field=models.CharField(max_length=50),
        ),
    ]
